type Artist {
    id: String
    name: String!

    tracks: [ArtistTrack!]
    albums: [ArtistAlbum!]
    productions: [ArtistProduction!]
}

type ArtistTrack {
    id: String
    title: String!
    audioUrl: String
    downloadUrl: String
    coverUrl: String
    artist: String
}

type ArtistAlbum {
    id: String
    title: String!
}

type ArtistProduction {
    id: String
    name: String!
}

extend type Query {
    getArtists: [Artist!]
    getArtistById(id: String!): Artist
}

extend type Mutation {
    createArtist(name: String!): Artist
}